version: '3.3'

services:
    db:
        image: postgres:12.0-alpine
        restart: always
        env_file:
            - ./.env

    backend:
        image: zloybaklan/rashtest:latest
        restart: always
        depends_on:
            - db
        env_file:
            - ./.env