version: '3.3'

services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        env_file:
            - ./.env

    backend:
        image: zloybaklan/rashtest:latest
        restart: always
        depends_on:
            - db
        env_file:
            - ./.env