version: '3.3'

services:
    db:
      image: postgres:12
      restart: always
      env_file:
            - ./.env

    backend:
        image: zloybaklan/rashtest:latest
        restart: always
        volumes:
            - static_value:/templates/
        depends_on:
        env_file:
            - ./.env