version: '3.3'

services:
    db:
      image: postgres

    backend:
        image: zloybaklan/RashTest:latest
        restart: always
        volumes:
            - static_value:/templates/
        depends_on:
        env_file:
            - ./.env