version: '3.3'

services:

    backend:
        image: zloybaklan/RashTest:latest
        restart: always
        volumes:
            - static_value:/templates/
        depends_on:
        env_file:
            - ./.env