# Generated by Django 4.1.1 on 2022-09-20 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'rub'), ('USD', 'usd')], default='USD', max_length=3, verbose_name='Стоимость пересчитается, по умолчанию укажите в рублях'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(help_text='Описание', max_length=200, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='На сайте оплаты в $', validators=[django.core.validators.MinValueValidator(0, 'Значение не может быть меньше 0')], verbose_name='Стоимость'),
        ),
    ]
