# Generated by Django 4.1.1 on 2022-09-20 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='На сайте оплаты(Stripe) в $', validators=[django.core.validators.MinValueValidator(0, 'Значение не может быть меньше 0')], verbose_name='Стоимость по умолчанию в рублях'),
        ),
    ]
