# Generated by Django 4.1.1 on 2022-09-20 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Значение не может быть меньше 0')], verbose_name='Стоимость по умолчанию в рублях'),
        ),
    ]
