# Generated by Django 4.1.1 on 2022-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'rub'), ('USD', 'usd'), ('EUR', 'eur')], default='RUB', max_length=3, verbose_name='Стоимость пересчитается, в $ по курсу ЦБРФ'),
        ),
    ]
