# Generated by Django 4.1.1 on 2022-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_tax_orders_tax_jurisdi_7c3e18_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['jurisdiction', 'tax_id'], name='orders_tax_jurisdi_7c3e18_idx'),
        ),
    ]
